# Generated by Django 5.2 on 2025-05-25 08:13

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='userlanguages',
            old_name='other_framework_name',
            new_name='other_language_name',
        ),
        migrations.AlterUniqueTogether(
            name='userframeworks',
            unique_together={('user_id', 'framework_id')},
        ),
        migrations.AlterUniqueTogether(
            name='userlanguages',
            unique_together={('user_id', 'language_id')},
        ),
        migrations.AlterUniqueTogether(
            name='usersocialmedias',
            unique_together={('user_id', 'social_media_id')},
        ),
    ]
