# Generated by Django 5.2 on 2025-05-25 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0002_rename_other_framework_name_userlanguages_other_language_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userframeworks',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='userlanguages',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='usersocialmedias',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
