# Generated by Django 5.2 on 2025-05-25 09:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0003_alter_userframeworks_id_alter_userlanguages_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userframeworks',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='userlanguages',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='usersocialmedias',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='userframeworks',
            constraint=models.UniqueConstraint(fields=('user_id', 'framework_id'), name='unique_user_framework'),
        ),
        migrations.AddConstraint(
            model_name='userlanguages',
            constraint=models.UniqueConstraint(fields=('user_id', 'language_id'), name='unique_user_language'),
        ),
        migrations.AddConstraint(
            model_name='usersocialmedias',
            constraint=models.UniqueConstraint(fields=('user_id', 'social_media_id'), name='unique_user_social_media'),
        ),
    ]
