# Generated by Django 5.2 on 2025-05-28 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0005_remove_userframeworks_unique_user_framework_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userframeworks',
            name='other_framework_name',
            field=models.CharField(blank=True, default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userlanguages',
            name='other_language_name',
            field=models.CharField(blank=True, default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usersocialmedias',
            name='other_social_media_name',
            field=models.CharField(blank=True, default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usersocialmedias',
            name='url',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
    ]
