# Generated by Django 5.2 on 2025-08-19 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='repository_url',
            field=models.URLField(blank=True, max_length=2000, null=True),
        ),
    ]
