# Generated by Django 5.2 on 2025-08-19 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0002_alter_project_repository_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='tags',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
