# Generated by Django 5.2 on 2025-08-19 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0003_remove_project_tags_delete_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='slug',
        ),
    ]
