# Generated by Django 5.2 on 2025-11-08 03:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0004_remove_project_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='cached_average_rating',
        ),
        migrations.RemoveField(
            model_name='project',
            name='ogp_image_url',
        ),
        migrations.RemoveField(
            model_name='review',
            name='rating',
        ),
    ]
