version: '3.9'

services:
  # backend:
  #   build:
  #     context: ./backend
  #   volumes:
  #     - ./backend:/app
  #   working_dir: /app
  #   command: >
  #     sh -c "python manage.py migrate &&
  #            python manage.py runserver 0.0.0.0:8000"
  #   ports:
  #     - "8000:8000"
  #   env_file: .env
  #   depends_on:
  #     - db

  frontend:
    build:
      context: ./frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    working_dir: /app
    command: npm run dev
    ports:
      - "3000:3000"

  db:
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - "33066:3306"

volumes:
  mysql-data: