# Generated by Django 5.2 on 2025-05-17 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_rename_user_name_user_username_user_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestUser',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('school_id', models.CharField(max_length=50, unique=True)),
                ('username', models.CharField(max_length=150, unique=True)),
                ('request_at', models.DateTimeField(auto_now_add=True)),
                ('is_created', models.BooleanField(default=False)),
                ('agreed_to_terms', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
