# Generated by Django 5.2 on 2025-05-17 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_requestuser_alter_user_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='requestuser',
            old_name='school_id',
            new_name='student_id',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='school_id',
            new_name='student_id',
        ),
    ]
